/* PRODUCTS.JS - Base de datos completa de Fraganze
   Estructura mejorada con información olfativa detallada
   Precios de decants en CRC (Colones Costarricenses) - Febrero 2026
*/

const PRODUCTS = [
    // NAUTICA - FRESH AQUATIC
    {
        id: "nautica-voyage",
        name: "Voyage",
        brand: "Nautica",
        category: "Fresh",
        genero: "Hombre",
        familia_olfativa: "Acuático Aromático",
        descripcion: "Fragancia fresca y marina que evoca la libertad del mar. Voyage es una fragancia dinámica con notas acuáticas limpias y un toque de especias. Perfecta para el hombre moderno que busca frescura y vitalidad en su día a día.",
        notas_salida: ["Bergamota", "Jengibre", "Frutas cítricas"],
        notas_corazon: ["Notas acuáticas", "Pimienta blanca", "Cardamomo"],
        notas_fondo: ["Ambroxan", "Almizcares", "Ámbar gris"],
        ocasion: ["Día", "Casual", "Deporte"],
        duracion: "6-8 horas",
        estacion: ["Primavera", "Verano"],
        full_bottle_price: "Consultar",
        image: "images/Perfume-Nautica-Voyage-100ml.png",
        decant_prices: { "2ml": 1200, "3ml": 1600, "5ml": 2100, "10ml": 4000 }
    },
    {
        id: "nautica-classic",
        name: "Classic",
        brand: "Nautica",
        category: "Fresh",
        genero: "Hombre",
        familia_olfativa: "Acuático Aromático",
        descripcion: "El clásico atemporal de Nautica. Una fragancia fresca y limpia que combina notas acuáticas con especias cálidas. Es la fragancia perfecta para quien valora la elegancia simplista y la frescura duradero.",
        notas_salida: ["Manzana", "Lavanda", "Bergamota"],
        notas_corazon: ["Notas amaderadas", "Cardamomo", "Cilantro"],
        notas_fondo: ["Cedro", "Almizcares", "Ámbar"],
        ocasion: ["Día", "Casual", "Trabajo"],
        duracion: "6-8 horas",
        estacion: ["Primavera", "Verano", "Otoño"],
        full_bottle_price: "Consultar",
        image: "images/Nautica-classic.png",
        decant_prices: { "2ml": 1200, "3ml": 1600, "5ml": 2100, "10ml": 4000 }
    },
    {
        id: "nautica-blue",
        name: "Blue",
        brand: "Nautica",
        category: "Fresh",
        genero: "Hombre",
        familia_olfativa: "Acuático Aromático",
        descripcion: "Exuberancia acuática envuelta en calidez. Blue combina notas frescas de mar con especias cálidas, creando un equilibrio perfecto entre energía y sofisticación.",
        notas_salida: ["Calabrote", "Bergamota", "Limón"],
        notas_corazon: ["Notas acuáticas", "Jengibre", "Iris"],
        notas_fondo: ["Musgo de roble", "Sándalo", "Almizcares"],
        ocasion: ["Día", "Casual"],
        duracion: "6-8 horas",
        estacion: ["Primavera", "Verano"],
        full_bottle_price: "Consultar",
        image: "images/Nautica-classic.png",
        decant_prices: { "2ml": 1200, "3ml": 1600, "5ml": 2100, "10ml": 4000 }
    },
    {
        id: "nautica-n83",
        name: "N-83",
        brand: "Nautica",
        category: "Fresh",
        genero: "Hombre",
        familia_olfativa: "Acuático Aromático",
        descripcion: "Nautica N83 es un viaje sensorial a través de ingredientes frescos y limpios. Es una fragancia versátil apta para cualquier ocasión, que combina sofisticación con accesibilidad.",
        notas_salida: ["Pomelo", "Melocotón", "Bergamota"],
        notas_corazon: ["Jazmín", "Violeta", "Nuez moscada"],
        notas_fondo: ["Madera de sándalo", "Almízcares", "Vetiver"],
        ocasion: ["Día", "Casual", "Deporte"],
        duracion: "6-8 horas",
        estacion: ["Total"],
        full_bottle_price: "Consultar",
        image: "images/nautica-n-83.png",
        decant_prices: { "2ml": 1200, "3ml": 1600, "5ml": 2100, "10ml": 4000 }
    },
    {
        id: "nautica-sport",
        name: "Sport",
        brand: "Nautica",
        category: "Fresh",
        genero: "Hombre",
        familia_olfativa: "Acuático Aromático",
        descripcion: "Una fragancia versátil y dinámica que fusiona frescura acuática con calidez aromática. Sport es ideal para el hombre activo que necesita algo que lo acompañe en cualquier actividad.",
        notas_salida: ["Piña", "Tomate", "Mandarina"],
        notas_corazon: ["Jengibre", "Cardamomo", "Cilantro"],
        notas_fondo: ["Cedro", "Musgo de roble", "Tabaco"],
        ocasion: ["Día", "Casual", "Deporte"],
        duracion: "6-8 horas",
        estacion: ["Primavera", "Verano", "Otoño"],
        full_bottle_price: "Consultar",
        image: "images/nautica-sport.png",
        decant_prices: { "2ml": 1200, "3ml": 1600, "5ml": 2100, "10ml": 4000 }
    },
    {
        id: "nautica-heritage",
        name: "Heritage",
        brand: "Nautica",
        category: "Fresh",
        genero: "Hombre",
        familia_olfativa: "Acuático Aromático",
        descripcion: "Heritage es un homenaje a la tradición náutica. Combina frescura acuática con matices amaderados para crear una fragancia sofisticada y elegante.",
        notas_salida: ["Limón", "Pera", "Bergamota"],
        notas_corazon: ["Jacinto", "Jazmín", "Pimienta blanca"],
        notas_fondo: ["Cedro", "Almizcares", "Ámbar"],
        ocasion: ["Día", "Casual", "Elegante"],
        duracion: "7-9 horas",
        estacion: ["Total"],
        full_bottle_price: "Consultar",
        image: "images/Nautica-heritage.png",
        decant_prices: { "2ml": 1200, "3ml": 1600, "5ml": 2100, "10ml": 4000 }
    },

    // HALLOWEEN - ORIENTAL & FLORAL
    {
        id: "halloween-tradicional-mujer",
        name: "Tradicional Mujer",
        brand: "Halloween",
        category: "Floral",
        genero: "Mujer",
        familia_olfativa: "Floral Frutal",
        descripcion: "La esencia femenina clásica de Halloween. Una fragancia floral y frutal que combina dulzura con sofisticación, perfecta para cualquier mujer que busque elegancia atemporal.",
        notas_salida: ["Bergamota", "Frambuesa", "Pimienta rosa"],
        notas_corazon: ["Rosa", "Jazmín", "Freesia"],
        notas_fondo: ["Sándalo", "Almizcares", "Vainilla"],
        ocasion: ["Día", "Noche", "Casual"],
        duracion: "6-8 horas",
        estacion: ["Total"],
        full_bottle_price: "Consultar",
        image: "images/halloween-mujer.png",
        decant_prices: { "2ml": 1200, "3ml": 1600, "5ml": 2100, "10ml": 4000 }
    },
    {
        id: "halloween-man-x",
        name: "Man X",
        brand: "Halloween",
        category: "Aromatic",
        genero: "Hombre",
        familia_olfativa: "Aromático Especiado",
        descripcion: "Man X es una declaración de masculinidad moderna. Combina aromas especiados cálidos con un toque de frescura. Una fragancia potente y seductora.",
        notas_salida: ["Piamontés", "Jengibre", "Pimienta"],
        notas_corazon: ["Canela", "Cardamomo", "Clavo"],
        notas_fondo: ["Ámbar", "Cedro", "Cuero"],
        ocasion: ["Noche", "Ocasión especial"],
        duracion: "8-10 horas",
        estacion: ["Otoño", "Invierno"],
        full_bottle_price: "Consultar",
        image: "images/halloween-man-x.png",
        decant_prices: { "2ml": 1200, "3ml": 1600, "5ml": 2100, "10ml": 4000 }
    },
    {
        id: "halloween-man-rock-on",
        name: "Man Rock On",
        brand: "Halloween",
        category: "Aromatic",
        genero: "Hombre",
        familia_olfativa: "Aromático Especiado",
        descripcion: "Rock On es para el hombre que vive sin reglas. Una fragancia fuerte y desafiante que combina especias cálidas con un toque rebelde.",
        notas_salida: ["Bergamota", "Cardamomo", "Hinojo"],
        notas_corazon: ["Pimienta negra", "Anís", "Cilantro"],
        notas_fondo: ["Ámbar", "Cuero", "Madera de agar"],
        ocasion: ["Noche", "Ocasión especial"],
        duracion: "8-10 horas",
        estacion: ["Otoño", "Invierno"],
        full_bottle_price: "Consultar",
        image: "images/halloween-man-rock-on.png",
        decant_prices: { "2ml": 1200, "3ml": 1600, "5ml": 2100, "10ml": 4000 }
    },
    {
        id: "halloween-kiss-sexy",
        name: "Kiss Sexy",
        brand: "Halloween",
        category: "Floral",
        genero: "Mujer",
        familia_olfativa: "Floral Frutal Gourmand",
        descripcion: "Sensualidad pura. Kiss Sexy es una fragancia floral frutal gourmand que despierta los sentidos. Dulce, sofisticada y irresistiblemente femenina.",
        notas_salida: ["Frambuesa", "Piamontés", "Pomelo"],
        notas_corazon: ["Orquídea", "Peonía", "Flor de almendro"],
        notas_fondo: ["Caramelo", "Vainilla", "Almízcares"],
        ocasion: ["Noche", "Ocasión especial"],
        duracion: "7-9 horas",
        estacion: ["Total"],
        full_bottle_price: "Consultar",
        image: "images/halloween-kiss-sexy.png",
        decant_prices: { "2ml": 1200, "3ml": 1600, "5ml": 2100, "10ml": 4000 }
    },
    {
        id: "halloween-love",
        name: "Love",
        brand: "Halloween",
        category: "Floral",
        genero: "Mujer",
        familia_olfativa: "Floral Frutal",
        descripcion: "Amor en una botella. Love es una fragancia romántica y delicada que combina flores frescas con frutas dulces. Perfecta para expresar sentimientos.",
        notas_salida: ["Pimienta rosa", "Grosella negra", "Naranja"],
        notas_corazon: ["Peonia", "Rosa", "Jacinto"],
        notas_fondo: ["Sándalo", "Almizcares", "Ámbar blanco"],
        ocasion: ["Día", "Romántico"],
        duracion: "6-8 horas",
        estacion: ["Primavera", "Verano"],
        full_bottle_price: "Consultar",
        image: "images/halloween-love.png",
        decant_prices: { "2ml": 1200, "3ml": 1600, "5ml": 2100, "10ml": 4000 }
    },
    {
        id: "halloween-mia-me-mine",
        name: "Mia Me Mine",
        brand: "Halloween",
        category: "Floral",
        genero: "Mujer",
        familia_olfativa: "Floral Frutal Gourmand",
        descripcion: "Yo soy mía. Mia Me Mine es una declaración de independencia femenina. Floral, frutal y gourmand, con un toque de misterio.",
        notas_salida: ["Frambuesa", "Piña", "Mandarina"],
        notas_corazon: ["Flor de loto", "Muguete", "Jazmín"],
        notas_fondo: ["Vainilla", "Caramelo", "Almizcares"],
        ocasion: ["Día", "Noche", "Casual"],
        duracion: "6-8 horas",
        estacion: ["Total"],
        full_bottle_price: "Consultar",
        image: "images/Mía-Me-Mine-de-la-línea-Halloween-de-Jesús-del-Pozo.png",
        decant_prices: { "2ml": 1200, "3ml": 1600, "5ml": 2100, "10ml": 4000 }
    },

    // PERRY ELLIS 360 - VERSATILE COLLECTION
    {
        id: "perry-ellis-360-red",
        name: "360 Red",
        brand: "Perry Ellis",
        category: "Oriental",
        genero: "Mujer",
        familia_olfativa: "Oriental Frutal",
        descripcion: "Pasión y poder. 360 Red es una fragancia oriental que combina frutas cálidas con notas florales en el corazón. Para la mujer que se nota.",
        notas_salida: ["Piamontés", "Grosella negra", "Mandarina"],
        notas_corazon: ["Rosa", "Orquídea", "Lirio"],
        notas_fondo: ["Ámbar", "Cedro", "Vainilla"],
        ocasion: ["Noche", "Ocasión especial"],
        duracion: "8-10 horas",
        estacion: ["Otoño", "Invierno"],
        full_bottle_price: "Consultar",
        image: "images/380-red.png",
        decant_prices: { "2ml": 1200, "3ml": 1600, "5ml": 2100, "10ml": 4000 }
    },
    {
        id: "perry-ellis-360-blue",
        name: "360 Blue",
        brand: "Perry Ellis",
        category: "Fresh",
        genero: "Hombre",
        familia_olfativa: "Acuático Aromático",
        descripcion: "Frescura infinita. 360 Blue es una fragancia acuática fresca que combina notas cítricas con especias aromáticas. Versátil y sofisticada.",
        notas_salida: ["Pomelo", "Limón", "Bergamota"],
        notas_corazon: ["Notas acuáticas", "Pimienta blanca", "Cilantro"],
        notas_fondo: ["Cedro", "Musgo de roble", "Almizcares"],
        ocasion: ["Día", "Casual", "Deporte"],
        duracion: "6-8 horas",
        estacion: ["Primavera", "Verano"],
        full_bottle_price: "Consultar",
        image: "images/360-Blue.png",
        decant_prices: { "2ml": 1200, "3ml": 1600, "5ml": 2100, "10ml": 4000 }
    },
    {
        id: "perry-ellis-360-green",
        name: "360 Green",
        brand: "Perry Ellis",
        category: "Fresh",
        genero: "Unisex",
        familia_olfativa: "Acuático Aromático",
        descripcion: "Energía fresca. 360 Green es una fragancia luminosa que combina notas verdes frescas con especias aromáticas. Perfecta para cualquiera.",
        notas_salida: ["Bergamota", "Hoja de violeta", "Pomelo"],
        notas_corazon: ["Cilantro", "Cardamomo", "Iris"],
        notas_fondo: ["Vetiver", "Cedreno", "Almizcares"],
        ocasion: ["Día", "Casual"],
        duracion: "6-8 horas",
        estacion: ["Primavera", "Verano"],
        full_bottle_price: "Consultar",
        image: "images/360-Green.png",
        decant_prices: { "2ml": 1200, "3ml": 1600, "5ml": 2100, "10ml": 4000 }
    },
    {
        id: "perry-ellis-360-pink",
        name: "360 Pink",
        brand: "Perry Ellis",
        category: "Floral",
        genero: "Mujer",
        familia_olfativa: "Floral Frutal",
        descripcion: "Feminidad radiante. 360 Pink es una fragancia floral frutal que combina frescura con dulzura. Alegre, jovial y enormemente atractiva.",
        notas_salida: ["Pera", "Frambuesa", "Piamontés"],
        notas_corazon: ["Rosa", "Freesia", "Flor de almendro"],
        notas_fondo: ["Sándalo", "Almizcares", "Vainilla"],
        ocasion: ["Día", "Casual"],
        duracion: "6-8 horas",
        estacion: ["Primavera", "Verano"],
        full_bottle_price: "Consultar",
        image: "images/360-Pink.png",
        decant_prices: { "2ml": 1200, "3ml": 1600, "5ml": 2100, "10ml": 4000 }
    },
    {
        id: "perry-ellis-360-purple",
        name: "360 Purple",
        brand: "Perry Ellis",
        category: "Floral",
        genero: "Mujer",
        familia_olfativa: "Floral Frutal Gourmand",
        descripcion: "Misterio sofisticado. 360 Purple es una fragancia floral frutal gourmand. Combina notas frutales con flores delicadas y un toque de dulzura adictiva.",
        notas_salida: ["Grosella negra", "Piamontés", "Naranja"],
        notas_corazon: ["Violeta", "Lirio", "Jacinto"],
        notas_fondo: ["Ámbar", "Vainilla", "Almizcares"],
        ocasion: ["Día", "Noche"],
        duracion: "7-9 horas",
        estacion: ["Total"],
        full_bottle_price: "Consultar",
        image: "images/360-Purple.png",
        decant_prices: { "2ml": 1200, "3ml": 1600, "5ml": 2100, "10ml": 4000 }
    },
    {
        id: "perry-ellis-360-coral",
        name: "360 Coral",
        brand: "Perry Ellis",
        category: "Floral",
        genero: "Mujer",
        familia_olfativa: "Floral Frutal",
        descripcion: "Calidez tropical. 360 Coral captura la esencia del verano tropical. Floral frutal con especias cálidas que evocan playas de arena blanca.",
        notas_salida: ["Piña", "Melocotón", "Mandarina"],
        notas_corazon: ["Hibisco", "Ylang ylang", "Magnolia"],
        notas_fondo: ["Coco", "Vainilla", "Almizcares"],
        ocasion: ["Día", "Vacaciones"],
        duracion: "6-8 horas",
        estacion: ["Verano"],
        full_bottle_price: "Consultar",
        image: "images/360-Coral.png",
        decant_prices: { "2ml": 1200, "3ml": 1600, "5ml": 2100, "10ml": 4000 }
    },
    {
        id: "perry-ellis-360-white",
        name: "360 White",
        brand: "Perry Ellis",
        category: "Fresh",
        genero: "Unisex",
        familia_olfativa: "Acuático Aromático",
        descripcion: "Pureza luminosa. 360 White es una fragancia fresca y minimalista que combina notas limpias con un toque de sofisticación. Versátil y accesible.",
        notas_salida: ["Limón", "Bergamota", "Mandarina"],
        notas_corazon: ["Notas acuáticas", "Muguete", "Jazmín"],
        notas_fondo: ["Cedro", "Almizcares", "Musgo"],
        ocasion: ["Día", "Casual", "Deporte"],
        duracion: "6-8 horas",
        estacion: ["Total"],
        full_bottle_price: "Consultar",
        image: "images/360-White.png",
        decant_prices: { "2ml": 1200, "3ml": 1600, "5ml": 2100, "10ml": 4000 }
    },

    // GUESS COLLECTION
    {
        id: "guess-gold",
        name: "Gold",
        brand: "Guess",
        category: "Oriental",
        genero: "Mujer",
        familia_olfativa: "Oriental Gourmand",
        descripcion: "Lujo dorado. Gold es una fragancia oriental gourmand que combina la calidez de la vainilla con notas florales exóticas. Sofisticada y seductora.",
        notas_salida: ["Mandarina", "Pomelo", "Jengibre"],
        notas_corazon: ["Orquídea", "Ylang ylang", "Ámbar gris"],
        notas_fondo: ["Vainilla", "Almizcares", "Ámbar"],
        ocasion: ["Noche", "Ocasión especial"],
        duracion: "8-10 horas",
        estacion: ["Total"],
        full_bottle_price: "Consultar",
        image: "images/guess-gold.png",
        decant_prices: { "2ml": 1200, "3ml": 1600, "5ml": 2100, "10ml": 4000 }
    },
    {
        id: "guess-seductive",
        name: "Seductive",
        brand: "Guess",
        category: "Oriental",
        genero: "Mujer",
        familia_olfativa: "Oriental Floral",
        descripcion: "Seducción pura. Seductive es una fragancia oriental floral que combina flores exóticas con notas cálidas. Irresistiblemente atractiva y femenina.",
        notas_salida: ["Bergamota", "Pimienta rosa", "Jengibre"],
        notas_corazon: ["Rosa", "Orquídea", "Gardenia"],
        notas_fondo: ["Cedro", "Almizcares", "Ámbar"],
        ocasion: ["Noche", "Ocasión especial", "Romántico"],
        duracion: "8-10 horas",
        estacion: ["Otoño", "Invierno"],
        full_bottle_price: "Consultar",
        image: "images/guess-seductive.png",
        decant_prices: { "2ml": 1200, "3ml": 1600, "5ml": 2100, "10ml": 4000 }
    },
    {
        id: "guess-tradicional-mujer",
        name: "Tradicional Mujer",
        brand: "Guess",
        category: "Floral",
        genero: "Mujer",
        familia_olfativa: "Floral Frutal",
        descripcion: "La esencia clásica de Guess para mujer. Floral frutal que combina frescura con elegancia. Perfecta para cualquier ocasión.",
        notas_salida: ["Bergamota", "Piamontés", "Limón"],
        notas_corazon: ["Rosa", "Jazmín", "Lirio"],
        notas_fondo: ["Sándalo", "Almizcares", "Ámbar"],
        ocasion: ["Día", "Noche", "Total"],
        duracion: "6-8 horas",
        estacion: ["Total"],
        full_bottle_price: "Consultar",
        image: "images/guess-tradicional-mujer.png",
        decant_prices: { "2ml": 1200, "3ml": 1600, "5ml": 2100, "10ml": 4000 }
    },

    // DESIGNER & CELEBRITY FRAGRANCES
    {
        id: "ariana-grande-ari",
        name: "Ari",
        brand: "Ariana Grande",
        category: "Floral",
        genero: "Mujer",
        familia_olfativa: "Floral Frutal Gourmand",
        descripcion: "Dulce y juguetona. Ari es la fragancia signature de Ariana Grande. Combina notas frutales con flores delicadas y un toque de algodón dulce.",
        notas_salida: ["Frambuesa", "Pera", "Manzana"],
        notas_corazon: ["Jazmín", "Freesia", "Flor de loto"],
        notas_fondo: ["Caramelo", "Vainilla", "Almizcares"],
        ocasion: ["Día", "Casual", "Juvenil"],
        duracion: "6-8 horas",
        estacion: ["Primavera", "Verano"],
        full_bottle_price: "Consultar",
        image: "images/ari-by-ariana-grande.png",
        decant_prices: { "2ml": 1200, "3ml": 1600, "5ml": 2100, "10ml": 4000 }
    },
    {
        id: "katy-perry-meow",
        name: "Meow!",
        brand: "Katy Perry",
        category: "Floral",
        genero: "Mujer",
        familia_olfativa: "Floral Frutal",
        descripcion: "Juguetona y femenina. Meow es la fragancia playful de Katy Perry. Combina frutas dulces con flores frescas. Perfecta para la mujer joven y confiada.",
        notas_salida: ["Naranja", "Piamontés", "Mandarina"],
        notas_corazon: ["Rosa", "Jazmín", "Muguete"],
        notas_fondo: ["Vainilla", "Almizcares", "Ámbar"],
        ocasion: ["Día", "Casual"],
        duracion: "6-8 horas",
        estacion: ["Primavera", "Verano"],
        full_bottle_price: "Consultar",
        image: "images/Meow!-de-Katy-Perry.png",
        decant_prices: { "2ml": 1200, "3ml": 1600, "5ml": 2100, "10ml": 4000 }
    },
    {
        id: "britney-spears-fantasy",
        name: "Fantasy",
        brand: "Britney Spears",
        category: "Oriental",
        genero: "Mujer",
        familia_olfativa: "Oriental Frutal",
        descripcion: "Fantasía seductora. Fantasy es el fragancia signature de Britney Spears. Oriental fusionada con frutas deliciosas. Sensual y adictiva.",
        notas_salida: ["Frambuesa", "Bergamota", "Jengibre"],
        notas_corazon: ["Flor de almendro", "Rosa", "Lirio"],
        notas_fondo: ["Almizcares", "Vainilla", "Ámbar"],
        ocasion: ["Noche", "Ocasión especial"],
        duracion: "8-10 horas",
        estacion: ["Total"],
        full_bottle_price: "Consultar",
        image: "images/Fantasy-de-Britney-Spears.png",
        decant_prices: { "2ml": 1200, "3ml": 1600, "5ml": 2100, "10ml": 4000 }
    },
    {
        id: "britney-spears-midnight-fantasy",
        name: "Midnight Fantasy",
        brand: "Britney Spears",
        category: "Oriental",
        genero: "Mujer",
        familia_olfativa: "Oriental Frutal",
        descripcion: "La mitad oriental de Britney Spears. Midnight Fantasy es más oscura y sensual que su hermana. Notas frutales exóticas con acordes orientales profundos.",
        notas_salida: ["Grosella negra", "Bergamota", "Piamontés"],
        notas_corazon: ["Orquídea", "Lirio", "Ylang ylang"],
        notas_fondo: ["Almizcares", "Ámbar", "Vainilla"],
        ocasion: ["Noche", "Ocasión especial"],
        duracion: "8-10 horas",
        estacion: ["Otoño", "Invierno"],
        full_bottle_price: "Consultar",
        image: "images/Midnight-Fantasy-de-Britney-Spears.png",
        decant_prices: { "2ml": 1200, "3ml": 1600, "5ml": 2100, "10ml": 4000 }
    },
    {
        id: "tommy-hilfiger-hombre",
        name: "Tommy Hilfiger Hombre",
        brand: "Tommy Hilfiger",
        category: "Aromatic",
        genero: "Hombre",
        familia_olfativa: "Aromático Especiado",
        descripcion: "Clásico americano. Tommy Hilfiger Hombre es una fragancia aroática especiada que refleja la sensibilidad desenfadada del diseño Tommy.",
        notas_salida: ["Bergamota", "Pimienta", "Cardamomo"],
        notas_corazon: ["Anís", "Cilantro", "Jazmín"],
        notas_fondo: ["Cedro", "Almizcares", "Cuero"],
        ocasion: ["Día", "Casual", "Trabajo"],
        duracion: "6-8 horas",
        estacion: ["Total"],
        full_bottle_price: "Consultar",
        image: "images/tommy-hombre.png",
        decant_prices: { "2ml": 1200, "3ml": 1600, "5ml": 2100, "10ml": 4000 }
    },
    {
        id: "tommy-hilfiger-mujer",
        name: "Tommy Hilfiger Mujer",
        brand: "Tommy Hilfiger",
        category: "Floral",
        genero: "Mujer",
        familia_olfativa: "Floral Frutal",
        descripcion: "Femenino con actitud. Tommy Hilfiger Mujer es una fragancia floral frutal con un toque desenfadado. Fresca, activa y segura de sí misma.",
        notas_salida: ["Pera", "Frambuesa", "Bergamota"],
        notas_corazon: ["Rosa", "Freesia", "Jacinto"],
        notas_fondo: ["Sándalo", "Almizcares", "Vainilla"],
        ocasion: ["Día", "Casual"],
        duracion: "6-8 horas",
        estacion: ["Primavera", "Verano"],
        full_bottle_price: "Consultar",
        image: "images/tommy-girl.png",
        decant_prices: { "2ml": 1200, "3ml": 1600, "5ml": 2100, "10ml": 4000 }
    },
    {
        id: "victorinox",
        name: "Victorinox",
        brand: "Victorinox",
        category: "Aromatic",
        genero: "Hombre",
        familia_olfativa: "Aromático Especiado",
        descripcion: "Precisión suiza en forma de fragancia. Victorinox es una fragancia aroática especiada que refleja la excelencia y la fiabilidad de la marca.",
        notas_salida: ["Bergamota", "Pimienta blanca", "Hinojo"],
        notas_corazon: ["Cardamomo", "Cilantro", "Iris"],
        notas_fondo: ["Cedro", "Vetiver", "Almizcares"],
        ocasion: ["Día", "Trabajo", "Casual"],
        duracion: "6-8 horas",
        estacion: ["Total"],
        full_bottle_price: "Consultar",
        image: "images/Victorinox-ALTITUD.png",
        decant_prices: { "2ml": 1200, "3ml": 1600, "5ml": 2100, "10ml": 4000 }
    },

    // PREMIUM COLLECTION WITH SPECIAL PRICES
    {
        id: "acqua-di-gio-profondo",
        name: "Acqua di Gio Profondo",
        brand: "Giorgio Armani",
        category: "Fresh",
        genero: "Hombre",
        familia_olfativa: "Acuático Aromático",
        descripcion: "La redefinición marina de Acqua di Gio. Profondo es una inmersión en el océano azul profundo con notas acuáticas refrescantes combinadas con especias cálidas.",
        notas_salida: ["Pomelo", "Notas acuáticas", "Caccía di mare"],
        notas_corazon: ["Cardamomo", "Cilantro", "Nuez moscada"],
        notas_fondo: ["Cedro", "Almizcares", "Ambroxan"],
        ocasion: ["Día", "Deporte", "Casual"],
        duracion: "7-9 horas",
        estacion: ["Primavera", "Verano"],
        full_bottle_price: "Consultar",
        image: "images/Acqua-di-Gio-Profondo.png",
        decant_prices: { "2ml": 1500, "3ml": 1600, "5ml": 2100, "10ml": 5000 }
    },

    // RASASI HAWAS COLLECTION - SPECIAL PRICES
    {
        id: "rasasi-hawas-men",
        name: "Hawas Men",
        brand: "Rasasi",
        category: "Aromatic",
        genero: "Hombre",
        familia_olfativa: "Aromático Especiado",
        descripcion: "Poder absoluto. Hawas Men es una fragancia potente y desafiante. Especias orientales con notas amaderadas profundas. Para el hombre que sabe lo que quiere.",
        notas_salida: ["Bergamota", "Cardamomo", "Pimienta"],
        notas_corazon: ["Canela", "Clavo", "Incienso"],
        notas_fondo: ["Ámbar", "Cuero", "Madera de agar"],
        ocasion: ["Noche", "Ocasión especial"],
        duracion: "9-12 horas",
        estacion: ["Otoño", "Invierno"],
        full_bottle_price: "Consultar",
        image: "images/hawas-for-Men.png",
        decant_prices: { "2ml": 1400, "3ml": 1600, "5ml": 2100, "10ml": 5000 }
    },
    {
        id: "rasasi-hawas-ice",
        name: "Hawas Ice",
        brand: "Rasasi",
        category: "Fresh",
        genero: "Hombre",
        familia_olfativa: "Acuático Aromático",
        descripcion: "Frialdad refrescante. Hawas Ice combina la potencia de Hawas con frescura acuática. Una fragancia polar que mantiene la intensidad oriental.",
        notas_salida: ["Limón", "Calabrote", "Pimienta"],
        notas_corazon: ["Notas acuáticas", "Cardamomo", "Jengibre"],
        notas_fondo: ["Cedro", "Almizcares", "Ámbar"],
        ocasion: ["Día", "Deporte", "Casualidad"],
        duracion: "8-10 horas",
        estacion: ["Primavera", "Verano"],
        full_bottle_price: "Consultar",
        image: "images/Hawas-ice.png",
        decant_prices: { "2ml": 1400, "3ml": 1600, "5ml": 2100, "10ml": 5000 }
    },
    {
        id: "rasasi-hawas-black",
        name: "Hawas Black",
        brand: "Rasasi",
        category: "Woody",
        genero: "Hombre",
        familia_olfativa: "Oriental Amaderado",
        descripcion: "Seducción oscura. Hawas Black es la oscuridad absoluta en forma de fragancia. Maderas profundas con especias exóticas. Misterioso e irresistible.",
        notas_salida: ["Pimienta negra", "Jengibre", "Cardamomo"],
        notas_corazon: ["Incienso", "Ámbar gris", "Madera de agar"],
        notas_fondo: ["Cedro", "Almizcares", "Cuero"],
        ocasion: ["Noche", "Ocasión especial"],
        duracion: "9-12 horas",
        estacion: ["Otoño", "Invierno"],
        full_bottle_price: "Consultar",
        image: "images/Hawas-Black.png",
        decant_prices: { "2ml": 1400, "3ml": 1600, "5ml": 2100, "10ml": 5000 }
    },

    // LATTAFA YARA COLLECTION - SPECIAL PRICES
    {
        id: "lattafa-yara-candy",
        name: "Yara Candy",
        brand: "Lattafa",
        category: "Floral",
        genero: "Mujer",
        familia_olfativa: "Floral Frutal Gourmand",
        descripcion: "Dulzura celestial. Yara Candy es una fragancia floral frutal gourmand que combina frutas maduras con flores exóticas. Adictivamente dulce y seductora.",
        notas_salida: ["Frambuesa", "Pera", "Mandarina"],
        notas_corazon: ["Peonia", "Rosa", "Jazmín"],
        notas_fondo: ["Caramelo", "Algodón dulce", "Almizcares"],
        ocasion: ["Día", "Noche", "Casual"],
        duracion: "7-9 horas",
        estacion: ["Total"],
        full_bottle_price: "Consultar",
        image: "images/lattafa-yara-candy.png",
        decant_prices: { "2ml": 1300, "3ml": 1600, "5ml": 2100, "10ml": 4000 }
    },
    {
        id: "lattafa-yara-moi",
        name: "Yara Moi",
        brand: "Lattafa",
        category: "Floral",
        genero: "Mujer",
        familia_olfativa: "Floral Frutal Gourmand",
        descripcion: "Yo sola. Yara Moi es la declaración de una mujer que sabe lo que quiere. Floral frutal gourmand con un toque de sofisticación. Poderosa y femenina.",
        notas_salida: ["Piamontés", "Grosella negra", "Bergamota"],
        notas_corazon: ["Rosa", "Orquídea", "Lirio"],
        notas_fondo: ["Vainilla", "Ámbar", "Almizcares"],
        ocasion: ["Noche", "Ocasión especial"],
        duracion: "8-10 horas",
        estacion: ["Total"],
        full_bottle_price: "Consultar",
        image: "images/Yara-Moi.png",
        decant_prices: { "2ml": 1300, "3ml": 1600, "5ml": 2100, "10ml": 4000 }
    },
    {
        id: "lattafa-yara-tous",
        name: "Yara Tous",
        brand: "Lattafa",
        category: "Floral",
        genero: "Mujer",
        familia_olfativa: "Floral Frutal Gourmand",
        descripcion: "Para todos, para mí. Yara Tous es una fragancia que celebra la libertad y la individualidad. Floral frutal gourmand con notas especiadas cálidas.",
        notas_salida: ["Naranja", "Piña", "Cardamomo"],
        notas_corazon: ["Freesia", "Rosa", "Violeta"],
        notas_fondo: ["Vainilla", "Sándalo", "Almizcares"],
        ocasion: ["Día", "Noche", "Casual"],
        duracion: "7-9 horas",
        estacion: ["Total"],
        full_bottle_price: "Consultar",
        image: "images/lattafa-yara-tous.png",
        decant_prices: { "2ml": 1300, "3ml": 1600, "5ml": 2100, "10ml": 4000 }
    },

    // CLUB DE NUIT COLLECTION - SPECIAL PRICES
    {
        id: "club-de-nuit-untold",
        name: "Club de Nuit Untold",
        brand: "Armaf",
        category: "Woody",
        genero: "Hombre",
        familia_olfativa: "Oriental Amaderado",
        descripcion: "La historia no contada. Untold es una fragancia amaderada oriental que combina especias orientales con maderas profundas. Elegante, sofisticada y misteriosa.",
        notas_salida: ["Bergamota", "Cardamomo", "Pimienta"],
        notas_corazon: ["Incienso", "Canela", "Ámbar gris"],
        notas_fondo: ["Cedro", "Almizcares", "Cuero"],
        ocasion: ["Noche", "Ocasión especial"],
        duracion: "9-12 horas",
        estacion: ["Total"],
        full_bottle_price: "Consultar",
        image: "images/armaf-club-de-nuit-untold.png",
        decant_prices: { "2ml": 1300, "3ml": 1600, "5ml": 2100, "10ml": 4000 }
    },
    {
        id: "club-de-nuit-milestone",
        name: "Club de Nuit Milestone",
        brand: "Armaf",
        category: "Woody",
        genero: "Hombre",
        familia_olfativa: "Oriental Amaderado",
        descripcion: "Un hito en la excelencia. Milestone es un paso más allá en sofisticación. Amaderado oriental con toques de frutas secas. Durabilidad impresionante.",
        notas_salida: ["Frambuesa", "Bergamota", "Pimienta"],
        notas_corazon: ["Cardamomo", "Incienso", "Rosa"],
        notas_fondo: ["Cedro", "Almizcares", "Ámbar"],
        ocasion: ["Noche", "Ocasión especial"],
        duracion: "9-12 horas",
        estacion: ["Total"],
        full_bottle_price: "Consultar",
        image: "images/Decant-Club-de-Nuit-Milestone.png",
        decant_prices: { "2ml": 1300, "3ml": 1600, "5ml": 2100, "10ml": 4000 }
    },
    {
        id: "club-de-nuit-sillage",
        name: "Club de Nuit Sillage",
        brand: "Armaf",
        category: "Woody",
        genero: "Hombre",
        familia_olfativa: "Oriental Amaderado",
        descripcion: "Huella de excelencia. Sillage es la representación máxima de presencia. Amaderado oriental con proyección impresionante. Dejas tu marca donde quiera que vayas.",
        notas_salida: ["Jengibre", "Cardamomo", "Pimienta"],
        notas_corazon: ["Incienso", "Canela", "Ámbar gris"],
        notas_fondo: ["Cedro oscuro", "Almizcares", "Cuero"],
        ocasion: ["Noche", "Ocasión especial"],
        duracion: "10-12 horas",
        estacion: ["Total"],
        full_bottle_price: "Consultar",
        image: "images/Club-de-Nuit-Sillage.png",
        decant_prices: { "2ml": 1300, "3ml": 1600, "5ml": 2100, "10ml": 4000 }
    }
];

// Exportar productos (compatible con módulos y script global)
if (typeof module !== 'undefined' && module.exports) {
    module.exports = PRODUCTS;
}

// Para uso global en navegador
if (typeof window !== 'undefined') {
    window.PRODUCTS = PRODUCTS;
}
